const classrooms = [
  {
    id: 1,
    name: "Advanced Mathematics",
    teacher: "Dr. Smith",
    students: 24,
    color: "bg-gradient-to-br from-blue-500 to-blue-600",
    assignments: 3,
    nextClass: "Today 10:00 AM",
    progress: 85,
  },
  {
    id: 2,
    name: "Physics Laboratory",
    teacher: "Prof. Johnson",
    students: 18,
    color: "bg-gradient-to-br from-green-500 to-green-600",
    assignments: 2,
    nextClass: "Tomorrow 2:00 PM",
    progress: 92,
  },
  {
    id: 3,
    name: "English Literature",
    teacher: "Ms. Davis",
    students: 22,
    color: "bg-gradient-to-br from-purple-500 to-purple-600",
    assignments: 1,
    nextClass: "Today 1:00 PM",
    progress: 78,
  },
  {
    id: 4,
    name: "World History",
    teacher: "Mr. Wilson",
    students: 20,
    color: "bg-gradient-to-br from-orange-500 to-orange-600",
    assignments: 4,
    nextClass: "Friday 11:00 AM",
    progress: 88,
  },
  {
    id: 5,
    name: "Chemistry",
    teacher: "Dr. Brown",
    students: 16,
    color: "bg-gradient-to-br from-red-500 to-red-600",
    assignments: 2,
    nextClass: "Monday 9:00 AM",
    progress: 95,
  },
  {
    id: 6,
    name: "Computer Science",
    teacher: "Prof. Lee",
    students: 28,
    color: "bg-gradient-to-br from-teal-500 to-teal-600",
    assignments: 5,
    nextClass: "Today 3:00 PM",
    progress: 82,
  },
]
module.exports = classrooms